/**
 * This class is generated by jOOQ
 */
package tech.codingclub.helix.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SongsRecord extends org.jooq.impl.TableRecordImpl<tech.codingclub.helix.tables.records.SongsRecord> implements org.jooq.Record9<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = -1146720495;

	/**
	 * Setter for <code>public.Songs.parent_link</code>.
	 */
	public void setParentLink(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.Songs.parent_link</code>.
	 */
	public java.lang.String getParentLink() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>public.Songs.link</code>.
	 */
	public void setLink(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.Songs.link</code>.
	 */
	public java.lang.String getLink() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>public.Songs.album</code>.
	 */
	public void setAlbum(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.Songs.album</code>.
	 */
	public java.lang.String getAlbum() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>public.Songs.duration</code>.
	 */
	public void setDuration(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.Songs.duration</code>.
	 */
	public java.lang.String getDuration() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>public.Songs.singers</code>.
	 */
	public void setSingers(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.Songs.singers</code>.
	 */
	public java.lang.String getSingers() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>public.Songs.lyricist</code>.
	 */
	public void setLyricist(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.Songs.lyricist</code>.
	 */
	public java.lang.String getLyricist() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>public.Songs.music_director</code>.
	 */
	public void setMusicDirector(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>public.Songs.music_director</code>.
	 */
	public java.lang.String getMusicDirector() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>public.Songs.download_128</code>.
	 */
	public void setDownload_128(java.lang.String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>public.Songs.download_128</code>.
	 */
	public java.lang.String getDownload_128() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>public.Songs.download_256</code>.
	 */
	public void setDownload_256(java.lang.String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>public.Songs.download_256</code>.
	 */
	public java.lang.String getDownload_256() {
		return (java.lang.String) getValue(8);
	}

	// -------------------------------------------------------------------------
	// Record9 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row9<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row9) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row9<java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row9) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return tech.codingclub.helix.tables.Songs.SONGS.PARENT_LINK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return tech.codingclub.helix.tables.Songs.SONGS.LINK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return tech.codingclub.helix.tables.Songs.SONGS.ALBUM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return tech.codingclub.helix.tables.Songs.SONGS.DURATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return tech.codingclub.helix.tables.Songs.SONGS.SINGERS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return tech.codingclub.helix.tables.Songs.SONGS.LYRICIST;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return tech.codingclub.helix.tables.Songs.SONGS.MUSIC_DIRECTOR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return tech.codingclub.helix.tables.Songs.SONGS.DOWNLOAD_128;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field9() {
		return tech.codingclub.helix.tables.Songs.SONGS.DOWNLOAD_256;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getParentLink();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getLink();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getAlbum();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getDuration();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getSingers();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getLyricist();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getMusicDirector();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getDownload_128();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value9() {
		return getDownload_256();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SongsRecord value1(java.lang.String value) {
		setParentLink(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SongsRecord value2(java.lang.String value) {
		setLink(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SongsRecord value3(java.lang.String value) {
		setAlbum(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SongsRecord value4(java.lang.String value) {
		setDuration(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SongsRecord value5(java.lang.String value) {
		setSingers(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SongsRecord value6(java.lang.String value) {
		setLyricist(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SongsRecord value7(java.lang.String value) {
		setMusicDirector(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SongsRecord value8(java.lang.String value) {
		setDownload_128(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SongsRecord value9(java.lang.String value) {
		setDownload_256(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SongsRecord values(java.lang.String value1, java.lang.String value2, java.lang.String value3, java.lang.String value4, java.lang.String value5, java.lang.String value6, java.lang.String value7, java.lang.String value8, java.lang.String value9) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SongsRecord
	 */
	public SongsRecord() {
		super(tech.codingclub.helix.tables.Songs.SONGS);
	}

	/**
	 * Create a detached, initialised SongsRecord
	 */
	public SongsRecord(java.lang.String parentLink, java.lang.String link, java.lang.String album, java.lang.String duration, java.lang.String singers, java.lang.String lyricist, java.lang.String musicDirector, java.lang.String download_128, java.lang.String download_256) {
		super(tech.codingclub.helix.tables.Songs.SONGS);

		setValue(0, parentLink);
		setValue(1, link);
		setValue(2, album);
		setValue(3, duration);
		setValue(4, singers);
		setValue(5, lyricist);
		setValue(6, musicDirector);
		setValue(7, download_128);
		setValue(8, download_256);
	}
}
