/**
 * This class is generated by jOOQ
 */
package tech.codingclub.helix.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Songs extends org.jooq.impl.TableImpl<tech.codingclub.helix.tables.records.SongsRecord> {

	private static final long serialVersionUID = 212380768;

	/**
	 * The singleton instance of <code>public.Songs</code>
	 */
	public static final tech.codingclub.helix.tables.Songs SONGS = new tech.codingclub.helix.tables.Songs();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<tech.codingclub.helix.tables.records.SongsRecord> getRecordType() {
		return tech.codingclub.helix.tables.records.SongsRecord.class;
	}

	/**
	 * The column <code>public.Songs.parent_link</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.SongsRecord, java.lang.String> PARENT_LINK = createField("parent_link", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>public.Songs.link</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.SongsRecord, java.lang.String> LINK = createField("link", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>public.Songs.album</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.SongsRecord, java.lang.String> ALBUM = createField("album", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>public.Songs.duration</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.SongsRecord, java.lang.String> DURATION = createField("duration", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>public.Songs.singers</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.SongsRecord, java.lang.String> SINGERS = createField("singers", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>public.Songs.lyricist</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.SongsRecord, java.lang.String> LYRICIST = createField("lyricist", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>public.Songs.music_director</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.SongsRecord, java.lang.String> MUSIC_DIRECTOR = createField("music_director", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>public.Songs.download_128</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.SongsRecord, java.lang.String> DOWNLOAD_128 = createField("download_128", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>public.Songs.download_256</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.SongsRecord, java.lang.String> DOWNLOAD_256 = createField("download_256", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * Create a <code>public.Songs</code> table reference
	 */
	public Songs() {
		this("Songs", null);
	}

	/**
	 * Create an aliased <code>public.Songs</code> table reference
	 */
	public Songs(java.lang.String alias) {
		this(alias, tech.codingclub.helix.tables.Songs.SONGS);
	}

	private Songs(java.lang.String alias, org.jooq.Table<tech.codingclub.helix.tables.records.SongsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Songs(java.lang.String alias, org.jooq.Table<tech.codingclub.helix.tables.records.SongsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, tech.codingclub.helix.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public tech.codingclub.helix.tables.Songs as(java.lang.String alias) {
		return new tech.codingclub.helix.tables.Songs(alias, this);
	}

	/**
	 * Rename this table
	 */
	public tech.codingclub.helix.tables.Songs rename(java.lang.String name) {
		return new tech.codingclub.helix.tables.Songs(name, null);
	}
}
